name: ChemicalDiceG CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Always get latest stable Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas tqdm rdkit
          pip install https://github.com/ChemicalDice/ChemicalDiceG.git

      - name: Run tests
        run: pytest



